version: '3.4'

services:
  backend:
    build: backend
    ports:
      - 8082:8082
    volumes:
      - ./backend:/app
    entrypoint: /bin/bash -c "python manage.py runserver 0.0.0.0:8082"
  frontend:
    build: frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/projectroot
    depends_on:
      - backend
    entrypoint: /bin/sh
    environment:
      - NODE_ENV=development
    command: '-c "cd /projectroot && npm install && npm run dev --host"'
