version: '3.4'

services:
  backend:
    build: backend
    ports:
      - 8082:8082
    entrypoint: /bin/bash -c "python manage.py runserver 0.0.0.0:8082" # TODO
    environment:
      - DJANGO_DEBUG=False
  frontend:
    build: frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
