# Generated by Django 4.1.2 on 2022-10-22 22:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('length', models.IntegerField()),
                ('lock_in_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeetingSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_critical', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.meeting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTimeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('optimality', models.IntegerField()),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingProposalAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_committed', models.BooleanField()),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.meetingtimeproposal')),
                ('user_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.usermeetingsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_absolute', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.user')),
            ],
        ),
    ]
