# Generated by Django 4.1.1 on 2022-09-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MeetingTimeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("optimality", models.IntegerField()),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api_app.meeting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingProposalAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_committed", models.BooleanField()),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api_app.meetingtimeproposal",
                    ),
                ),
                (
                    "user_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api_app.usermeetingsubscription",
                    ),
                ),
            ],
        ),
    ]
