# Generated by Django 4.0 on 2022-10-12 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_commitment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='lock_in_duration',
        ),
        migrations.AddField(
            model_name='meeting',
            name='lock_in_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 20, 19, 40, 770820)),
            preserve_default=False,
        ),
    ]
