# Generated by Django 4.0 on 2022-10-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_meetingtimeproposal_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='length',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
