# Generated by Django 4.0 on 2022-10-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_meetingtimeproposal_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtimeproposal',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.meeting'),
        ),
        migrations.AlterField(
            model_name='usermeetingsubscription',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.meeting'),
        ),
        migrations.AlterField(
            model_name='usermeetingsubscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.user'),
        ),
    ]
