# Generated by Django 4.0 on 2022-10-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_meetingtimeproposal_meeting_and_more'),
        ('api_app', '0006_meeting_length'),
    ]

    operations = [
    ]
