# Generated by Django 4.0 on 2022-10-22 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_commitment_id_alter_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingproposalattendance',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.meetingtimeproposal'),
        ),
        migrations.AlterField(
            model_name='meetingproposalattendance',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.usermeetingsubscription'),
        ),
    ]
