#for sending our scheduled meetings back to google
from calendar_api.calendar_api import google_calendar_api
g = google_calendar_api()

attendees = []
start = {}

# import_(calendarId=*, body=None, supportsAttachments=None, conferenceDataVersion=None)
# Imports an event. This operation is used to add a private copy of an existing event to a calendar.

# Args:
#   calendarId: string, Calendar identifier. To retrieve calendar IDs call the calendarList.list method. If you want to access the primary calendar of the currently logged in user, use the "primary" keyword. (required)
#   body: object, The request body.
#     The object takes the form of:

requestBody = {
    # "attachments": [ # File attachments for the event. Currently only Google Drive attachments are supported.
    #     # In order to modify attachments the supportsAttachments request parameter should be set to True.
    #     # There can be at most 25 attachments per event,
    #   {
    #     "mimeType": "A String", # Internet media type (MIME type) of the attachment.
    #     "title": "A String", # Attachment title.
    #     "fileUrl": "A String", # URL link to the attachment.
    #         # For adding Google Drive file attachments use the same format as in alternateLink property of the Files resource in the Drive API.
    #         # Required when adding an attachment.
    #     "iconLink": "A String", # URL link to the attachment's icon. Read-only.
    #     "fileId": "A String", # ID of the attached file. Read-only.
    #         # For Google Drive files, this is the ID of the corresponding Files resource entry in the Drive API.
    #   },
    # ],
    "creator": { # The creator of the event. Read-only.
      "self": False, # Whether the creator corresponds to the calendar on which this copy of the event appears. Read-only. The default is False.
      "displayName": user_name, # The creator's name, if available.
      "email": user_email, # The creator's email address, if available.
      "id": user_id, # The creator's Profile ID, if available. It corresponds to the id field in the People collection of the Google+ API
    },
    "organizer": { # The organizer of the event. If the organizer is also an attendee, this is indicated with a separate entry in attendees with the organizer field set to True. To change the organizer, use the move operation. Read-only, except when importing an event.
      "self": False, # Whether the organizer corresponds to the calendar on which this copy of the event appears. Read-only. The default is False.
      "displayName": user_name, # The organizer's name, if available.
      "email": user_email, # The organizer's email address, if available. It must be a valid email address as per RFC5322.
      "id": user_id, # The organizer's Profile ID, if available. It corresponds to the id field in the People collection of the Google+ API
    },
    "summary": title, # Title of the event.
    # "id": "A String", # Opaque identifier of the event. When creating new single or recurring events, you can specify their IDs. Provided IDs must follow these rules:
        # - characters allowed in the ID are those used in base32hex encoding, i.e. lowercase letters a-v and digits 0-9, see section 3.1.2 in RFC2938
        # - the length of the ID must be between 5 and 1024 characters
        # - the ID must be unique per calendar  Due to the globally distributed nature of the system, we cannot guarantee that ID collisions will be detected at event creation time. To minimize the risk of collisions we recommend using an established UUID algorithm such as one described in RFC4122.
        # If you do not specify an ID, it will be automatically generated by the server.
        # Note that the icalUID and the id are not identical and only one of them should be supplied at event creation time. One difference in their semantics is that in recurring events, all occurrences of one event have different ids while they all share the same icalUIDs.
    # "hangoutLink": "A String", # An absolute link to the Google+ hangout associated with this event. Read-only.
    "attendees": [ # The attendees of the event. See the Events with attendees guide for more information on scheduling events with other calendar users.
      {
        "comment": attendee_comment, # The attendee's response comment. Optional.
        "displayName": attendee_name, # The attendee's name, if available. Optional.
        "responseStatus": attendee_response, # The attendee's response status. Possible values are:
            # - "needsAction" - The attendee has not responded to the invitation.
            # - "declined" - The attendee has declined the invitation.
            # - "tentative" - The attendee has tentatively accepted the invitation.
            # - "accepted" - The attendee has accepted the invitation.
        "self": False, # Whether this entry represents the calendar on which this copy of the event appears. Read-only. The default is False.
        "id": attendee_id, # The attendee's Profile ID, if available. It corresponds to the id field in the People collection of the Google+ API
        # "additionalGuests": 0, # Number of additional guests. Optional. The default is 0.
        "resource": False, # Whether the attendee is a resource. Can only be set when the attendee is added to the event for the first time. Subsequent modifications are ignored. Optional. The default is False.
        "organizer": False, # Whether the attendee is the organizer of the event. Read-only. The default is False.
        # "optional": False, # Whether this is an optional attendee. Optional. The default is False.
        "email": attendee_email, # The attendee's email address, if available. This field must be present when adding an attendee. It must be a valid email address as per RFC5322.
            # Required when adding an attendee.
      },
    ],
    "start": { # The (inclusive) start time of the event. For a recurring event, this is the start time of the first instance.
      "date": "A String", # The date, in the format "yyyy-mm-dd", if this is an all-day event.
      "timeZone": "A String", # The time zone in which the time is specified. (Formatted as an IANA Time Zone Database name, e.g. "Europe/Zurich".) For recurring events this field is required and specifies the time zone in which the recurrence is expanded. For single events this field is optional and indicates a custom time zone for the event start/end.
      "dateTime": "A String", # The time, as a combined date-time value (formatted according to RFC3339). A time zone offset is required unless a time zone is explicitly specified in timeZone.
    },
    # "htmlLink": "A String", # An absolute link to this event in the Google Calendar Web UI. Read-only.
    # "recurrence": [ # List of RRULE, EXRULE, RDATE and EXDATE lines for a recurring event, as specified in RFC5545. Note that DTSTART and DTEND lines are not allowed in this field; event start and end times are specified in the start and end fields. This field is omitted for single events or instances of recurring events.
    #   "A String", #TODO: FIGURE THIS OUT
    # ],
    "source": { # Source from which the event was created. For example, a web page, an email message or any document identifiable by an URL with HTTP or HTTPS scheme. Can only be seen or modified by the creator of the event.
      "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ", #TODO: REPLACE WITH OUR LINK # URL of the source pointing to a resource. The URL scheme must be HTTP or HTTPS.
      "title": "Scalander", # Title of the source; for example a title of a web page or an email subject.
    },
    # "etag": "A String", # TODO: FIGURE THIS OUT # ETag of the resource.
    "location": location, # Geographic location of the event as free-form text. Optional.
    # "recurringEventId": "A String", #TODO: FIGURE THIS OUT # For an instance of a recurring event, this is the id of the recurring event to which this instance belongs. Immutable.
    # "gadget": { # A gadget that extends this event. #TODO: WHAT EVEN IS THIS
    #   "preferences": { # Preferences.
    #     "a_key": "A String", # The preference name and corresponding value.
    #   },
    #   "title": "A String", # The gadget's title.
    #   "height": 42, # The gadget's height in pixels. The height must be an integer greater than 0. Optional.
    #   "width": 42, # The gadget's width in pixels. The width must be an integer greater than 0. Optional.
    #   "link": "A String", # The gadget's URL. The URL scheme must be HTTPS.
    #   "type": "A String", # The gadget's type.
    #   "display": "A String", # The gadget's display mode. Optional. Possible values are:
    #       # - "icon" - The gadget displays next to the event's title in the calendar view.
    #       # - "chip" - The gadget displays when the event is clicked.
    #   "iconLink": "A String", # The gadget's icon URL. The URL scheme must be HTTPS.
    # },
    "status": status, # Status of the event. Optional. Possible values are:
        # - "confirmed" - The event is confirmed. This is the default status.
        # - "tentative" - The event is tentatively confirmed.
        # - "cancelled" - The event is cancelled (deleted). The list method returns cancelled events only on incremental sync (when syncToken or updatedMin are specified) or if the showDeleted flag is set to True. The get method always returns them.
        # A cancelled status represents two different states depending on the event type:
        # - Cancelled exceptions of an uncancelled recurring event indicate that this instance should no longer be presented to the user. Clients should store these events for the lifetime of the parent recurring event.
        # Cancelled exceptions are only guaranteed to have values for the id, recurringEventId and originalStartTime fields populated. The other fields might be empty.
        # - All other cancelled events represent deleted events. Clients should remove their locally synced copies. Such cancelled events will eventually disappear, so do not rely on them being available indefinitely.
        # Deleted events are only guaranteed to have the id field populated.   On the organizer's calendar, cancelled events continue to expose event details (summary, location, etc.) so that they can be restored (undeleted). Similarly, the events to which the user was invited and that they manually removed continue to provide details. However, incremental sync requests with showDeleted set to False will not return these details.
        # If an event changes its organizer (for example via the move operation) and the original organizer is not on the attendee list, it will leave behind a cancelled event where only the id field is guaranteed to be populated.
    "updated": current_time, # Last modification time of the event (as a RFC3339 timestamp). Read-only.
    "description": description, # Description of the event. Can contain HTML. Optional.
    "iCalUID": "A String", # Event unique identifier as defined in RFC5545. It is used to uniquely identify events accross calendaring systems and must be supplied when importing events via the import method.
        # Note that the icalUID and the id are not identical and only one of them should be supplied at event creation time. One difference in their semantics is that in recurring events, all occurrences of one event have different ids while they all share the same icalUIDs.
    "extendedProperties": { # Extended properties of the event.
      "shared": { # Properties that are shared between copies of the event on other attendees' calendars.
        "a_key": "A String", # The name of the shared property and the corresponding value.
      },
      "private": { # Properties that are private to the copy of the event that appears on this calendar.
        "a_key": "A String", # The name of the private property and the corresponding value.
      },
    },
    "endTimeUnspecified": False, # Whether the end time is actually unspecified. An end time is still provided for compatibility reasons, even if this attribute is set to True. The default is False.
    "sequence": 42, # Sequence number as per iCalendar.
    "visibility": "default", # Visibility of the event. Optional. Possible values are:
        # - "default" - Uses the default visibility for events on the calendar. This is the default value.
        # - "public" - The event is public and event details are visible to all readers of the calendar.
        # - "private" - The event is private and only event attendees may view event details.
        # - "confidential" - The event is private. This value is provided for compatibility reasons.
    "guestsCanModify": False, # Whether attendees other than the organizer can modify the event. Optional. The default is False.
    "end": { # The (exclusive) end time of the event. For a recurring event, this is the end time of the first instance.
      "date": "A String", # The date, in the format "yyyy-mm-dd", if this is an all-day event.
      "timeZone": "A String", # The time zone in which the time is specified. (Formatted as an IANA Time Zone Database name, e.g. "Europe/Zurich".) For recurring events this field is required and specifies the time zone in which the recurrence is expanded. For single events this field is optional and indicates a custom time zone for the event start/end.
      "dateTime": "A String", # The time, as a combined date-time value (formatted according to RFC3339). A time zone offset is required unless a time zone is explicitly specified in timeZone.
    },
    "attendeesOmitted": False, # Whether attendees may have been omitted from the event's representation. When retrieving an event, this may be due to a restriction specified by the maxAttendee query parameter. When updating an event, this can be used to only update the participant's response. Optional. The default is False.
    "kind": "calendar#event", # Type of the resource ("calendar#event").
    "locked": False, # Whether this is a locked event copy where no changes can be made to the main event fields "summary", "description", "location", "start", "end" or "recurrence". The default is False. Read-Only.
    "anyoneCanAddSelf": False, # Whether anyone can invite themselves to the event (currently works for Google+ events only). Optional. The default is False.
    "colorId": "A String", # The color of the event. This is an ID referring to an entry in the event section of the colors definition (see the  colors endpoint). Optional.
    "created": "A String", # Creation time of the event (as a RFC3339 timestamp). Read-only.
    "reminders": { # Information about the event's reminders for the authenticated user.
    #   "overrides": [ # If the event doesn't use the default reminders, this lists the reminders specific to the event, or, if not set, indicates that no reminders are set for this event. The maximum number of override reminders is 5.
    #     {
    #       "minutes": 42, # Number of minutes before the start of the event when the reminder should trigger. Valid values are between 0 and 40320 (4 weeks in minutes).
    #           # Required when adding a reminder.
    #       "method": "A String", # The method used by this reminder. Possible values are:
    #           # - "email" - Reminders are sent via email.
    #           # - "popup" - Reminders are sent via a UI popup.
    #           # Required when adding a reminder.
    #     },
    #   ],
      "useDefault": True, # Whether the default reminders of the calendar apply to the event.
    },
    "guestsCanSeeOtherGuests": True, # Whether attendees other than the organizer can see who the event's attendees are. Optional. The default is True.
    "originalStartTime": { # For an instance of a recurring event, this is the time at which this event would start according to the recurrence data in the recurring event identified by recurringEventId. It uniquely identifies the instance within the recurring event series even if the instance was moved to a different time. Immutable.
      "date": "A String", # The date, in the format "yyyy-mm-dd", if this is an all-day event.
      "timeZone": "A String", # The time zone in which the time is specified. (Formatted as an IANA Time Zone Database name, e.g. "Europe/Zurich".) For recurring events this field is required and specifies the time zone in which the recurrence is expanded. For single events this field is optional and indicates a custom time zone for the event start/end.
      "dateTime": "A String", # The time, as a combined date-time value (formatted according to RFC3339). A time zone offset is required unless a time zone is explicitly specified in timeZone.
    },
    "transparency": "opaque", # Whether the event blocks time on the calendar. Optional. Possible values are:
        # - "opaque" - Default value. The event does block time on the calendar. This is equivalent to setting Show me as to Busy in the Calendar UI.
        # - "transparent" - The event does not block time on the calendar. This is equivalent to setting Show me as to Available in the Calendar UI.
    "privateCopy": False, # If set to True, Event propagation is disabled. Note that it is not the same thing as Private event properties. Optional. Immutable. The default is False.
    
    #structure copied from https://google-api-client-libraries.appspot.com/documentation/calendar/v3/python/latest/calendar_v3.events.html#import_
  }